name: Spell Check

on:
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install aspell
        run: sudo apt-get install aspell

      - name: Spell check markdown files
        run: |
          for file in $(git diff --name-only --diff-filter=d "$(git log -1 --format='%H')"); do
            if [[ $file == *.md ]]; then
              aspell --lang=en list -t "$file"
            fi
          done
