name: Spell Check

on:
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install aspell
        run: sudo apt-get install aspell

      - name: Spell check markdown files
        run: aspell --lang=en list -t <(git show $(git log -1 --format="%H") --name-only)
